[listener]
type="raw"
interfaces=["ens3"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://127.0.0.1:9200/honeytrap-sensor"

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"
