version: "2.1"
services:
  elasticsearch:
    # image: elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
    networks:
      - honeytrap
  kibana:
    # image: kibana:latest
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - "127.0.0.1:5601:5601"
    # volumes:
      # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - XPACK_SECURITY_ENABLED=false
      # - ELASTICSEARCH_USER=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
        elasticsearch:
            condition: service_healthy
    networks:
      - honeytrap
networks:
  honeytrap:
    external: true
